### ISSUE TITLE
Pipes dont Update tileentity/Comparator issue

### ISSUE THREAD

**Issue by AlmightyAnubis** [EngineHub/CraftBook#1274]
**Versions**

CraftBook version: 3.10.4-SNAPSHOP;4720-1ecdd88
Paper version git-Paper-79 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: a831634)

**Describe the bug**
The pipes don't update the tileentity they put items in or extract items from, so comparators get stuck. In forge they need to be marked dirty, maybe there is something similar here too.

**To Reproduce**

1. Put pipe on hopper
2. put comparator on hopper
3. put item in hopper
4. extract item via pipe
5. comparator stays on

**Expected behavior**

Tileentity should update, so comparators can react.

**Screenshots**

![2021-07-06_18 35 45](https://user-images.githubusercontent.com/62308030/124637391-feb39580-de89-11eb-8b19-2bf88e45eb5f.png)

**Additional context**

**Comment by me4502** [comment]
This is an issue with Spigot. In order to correctly update these, every single chest interaction must be magnitudes slower, even ones that do not update the comparator.

This speed decrease is way too severe in order to be feasible. Until Spigot makes it possible to activate the comparator without a massive speed decrease this can't happen.
