### ISSUE TITLE
BetterLeads problems

### ISSUE THREAD

**Issue by JasonHorkles** [EngineHub/CraftBook#1280]
**Versions**

![image](https://user-images.githubusercontent.com/51760372/134786998-56f1a4e3-cd4b-426b-a120-20e3af9dcf15.png)

**Describe the bug**
When a player clicks a mob defined in the BetterLeads list with a lead, it removes 1 lead from the player even if they already have a lead on it, resulting in them losing that lead

**To Reproduce**

1. Leash a mob that's in the list
2. Click it with another lead
3. See it disappear

**Expected behavior**
It should behave like vanilla and pop the lead off iirc

**Screenshots**
N/A

**Additional context**
https://github.com/SilverstoneMC/Silverstone/issues/36

**Comment by me4502** [comment]
BetterLeads in CraftBook 3 was impacted by some Spigot bugs semi-recently, it's possible this is due to that. You're better off using CraftBook 5's BetterLeads as it uses stuff I added to Paper to make it work better (due to Spigot limitations). In general, there's not much that can be done to fix CraftBook 3 issues as they're issues in Spigot itself, CraftBook 5 drops Spigot support to be Paper only, and therefore allows things to be fixed.

**Comment by JasonHorkles** [comment]
Is there a download for v5 or is it still pretty new

**Comment by me4502** [comment]
> Is there a download for v5 or is it still pretty new

All info about it is in the pins of the CraftBook channel in the discord

**Comment by JasonHorkles** [comment]
After some testing, the issue still occurs on v5

Another issue is that the config requires 2 of the same mob to work, but with one having `minecraft:` in front
Example of working config:
![image](https://user-images.githubusercontent.com/51760372/134829635-5c5fcae2-7c7f-4920-97ce-6164872bfe5f.png)

**Comment by me4502** [comment]
Issue worked around in https://github.com/EngineHub/CraftBook/commit/e5d91d385c690db9e6e562220e6100ee465c3939
