### ISSUE TITLE
Could not pass event ChunkLoadEvent to CraftBook v3.10.7;4761-11ee8f6

### ISSUE THREAD

**Issue by arima0k** [EngineHub/CraftBook#1309]
### CraftBook Version

CraftBook version 3.10.7

### Platform Version

Paper version git-Paper-138 (MC: 1.19.2)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of CraftBook compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

[latest.log](https://github.com/EngineHub/CraftBook/files/9478439/latest.log)

[report.txt](https://github.com/EngineHub/CraftBook/files/9478409/report.txt)

### Expected Behavior

No idea, not a big error in console?

### Reproduction Steps

1. No idea, enabling the?:
Loaded Mechanics
----------------

VariableManager: package com.sk89q.craftbook.mechanics.variables
BetterPhysics  : package com.sk89q.craftbook.mechanics
Snow           : package com.sk89q.craftbook.mechanics
BetterPlants   : package com.sk89q.craftbook.mechanics

### Anything Else?

https://spark.lucko.me/P2UxlAl0Jm

**Comment by me4502** [comment]
This looks to be a server bug, not CraftBook. The chunk loaded event is being sent by Paper, at which point CraftBook is checking temperatures etc in the chunk. But the chunk isn’t actually loaded, so checking the temperature is causing a chunk load, which is sending the event again before the chunk is loaded, resulting in an infinite loop.

The issue is the event is firing too early, which isn’t possible for CraftBook to do anything about as that event means the chunk is usable now

**Comment by arima0k** [comment]
Could be the latest commits of paper about the `ChunkProviderServer`?

**Comment by me4502** [comment]
It looks like they've rewritten chunk loading, so very likely
